### main  page
GET http://localhost:3000/

### test
GET http://localhost:3000/test

### GET all students
GET http://localhost:3000/api/students

### GET single student
GET http://localhost:3000/api/students/3

### POST create student
POST http://localhost:3000/api/students
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXIiOnsiZW1haWwiOiJqYW1lc0Bib25kIiwiaWQiOjEsInNjb3BlIjoibWFuYWdlciJ9LCJpYXQiOjE3MDY2OTQ4MTEsImV4cCI6MTcwNjY5ODQxMX0.q9507ewjTeDbT_6he12YbK7EOlAOSLTvV9KhVORPfk4

{
    "firstname": "James",
    "lastname": "Bond",
    "email": "james@bond"
}

### PUT update student
PUT http://localhost:3000/api/students/1
Content-Type: application/json

{
    "firstName": "Vika",
    "lastName": "Vika",
    "email": "vika@vika"
}

### DELETE delete student
DELETE  http://localhost:3000/api/students/4

### POST register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "james@bond",
    "password": "123456"
}

### POST login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "james@bond",
    "password": "123456"
}